name: Build and push

on:
  push:
    branches:
      - build-cli


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Build CLI App
        run: mvn clean package -DskipTests
        working-directory: ./cli

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: zapp-cli
          path: dist